### PR TITLE
Vault Connection Partial Content Responses

### PR DESCRIPTION
**Pull request by broderickhyman**
This PR allows for the ability to receive partial file responses using the ArasVaultConnection from a IConnection.
The changes:
1. A DownloadRaw function that returns the HttpResponse instead of just a stream
2. Returning the Content Headers in the HttpResponse
3. Making the internal ArasVaultConnection accessible publicly
We thought about making a ProcessRaw and UploadRaw in order to match the DownloadRaw but the scope of changes quickly grew.

### CODE REVIEW

**Comment by erdomke** [comment]
I pushed a commit that I think should cover this a touch more cleanly. Now, when `Stream Process()` returns a `Stream`, that stream actually implements `IHttpResponse`, so you can get the headers.

**Comment by broderickhyman** [comment]
@erdomke Do you have any ideas going forward for better coordination? For larger changes should we create an issue with a proposal that you would respond to with at least a gut check within a week or two? I can see how your approach is cleaner but we have had these changes for almost 3 months and have written production code that will need to be adjusted for your code. I also don't want to be in a position where we have to wait a month before starting on improvements.

**Comment by erdomke** [comment]
What you're really asking is how can I either (1) not be opinionated or (2) be more timely with working on this 😉 . The answer to that is I simply need to do better. Sorry for the lengthy delay on this one.

**Comment by broderickhyman** [comment]
Just read my message again, I don't think I phrased it correctly, I wasn't trying to blame you, sorry! I am wondering if there is a better flow for ideas/changes where we can post and get just a quick response within a week or two from you like: "Yes that change makes sense, but instead of implementing X, implement Y". Then we can go write the code in a coordinated way that has a better chance of approval and it doesn't matter if PRs sit open for a month. I just don't know where the cutoff is for what needs a discussion before development work, or if maybe we should have a slack channel, etc.

**Comment by erdomke** [comment]
You're totally fine. I can try and be better about monitoring and responding to issues on the repo. Otherwise, I'm good to try a Slack channel or something of that nature.

**Comment by broderickhyman** [comment]
The code you wrote for this does not work in .Net 3.5 and breaks the nuget creation (HttpContent does not exist and Stream does not have WriteAsync or ReadAsync). Thoughts going forward on this one?

**Comment by erdomke** [comment]
The build is now fixed. Thanks for the heads up.

Eric

**Pull request closed without merging**
